"""All 28 TAM question texts. Keys must match ALL_Q_IDS exactly."""
 
QUESTIONS = {
    # Q4 — Behavioral Intention (scale_agree)
    'q4_1':  ('Q4. To what extent do you agree that...',
              'I intend to use ChatGPT to help me plan vacations/holidays in the future'),
    'q4_2':  ('Q4. To what extent do you agree that...',
              'I predict I will use ChatGPT for vacation/holiday planning in the future'),
    'q4_3':  ('Q4. To what extent do you agree that...',
              'I plan to use ChatGPT to learn more about vacation/holiday locations'),
    'q4_4':  ('Q4. To what extent do you agree that...',
              'The use of ChatGPT could increase my likelihood of going to a specific location'),
    'q4_5':  ('Q4. To what extent do you agree that...',
              'I would consider checking vacation/holiday prices using ChatGPT'),
    'q4_6':  ('Q4. To what extent do you agree that...',
              'ChatGPT increases my willingness to use specific hotels or restaurants'),
    'q4_7':  ('Q4. To what extent do you agree that...',
              'I will recommend ChatGPT to friends and family for vacation/holiday planning'),
    # Q5 — Perceived Usefulness (scale_agree)
    'q5_1':  ('Q5. To what extent do you agree that using ChatGPT...',
              'can speed up vacation/holiday planning'),
    'q5_2':  ('Q5. To what extent do you agree that using ChatGPT...',
              'would let me research for a vacation/holiday more quickly'),
    'q5_3':  ('Q5. To what extent do you agree that using ChatGPT...',
              'would improve the results of my vacation/holiday planning research'),
    'q5_4':  ('Q5. To what extent do you agree that using ChatGPT...',
              'would improve the effectiveness of my vacation/holiday planning research'),
    'q5_5':  ('Q5. To what extent do you agree that using ChatGPT...',
              'can improve the efficiency of vacation/holiday planning'),
    'q5_6':  ('Q5. To what extent do you agree that using ChatGPT...',
              'can enhance the completeness of vacation/holiday planning'),
    'q5_7':  ('Q5. To what extent do you agree that using ChatGPT...',
              'can enable accurate vacation/holiday planning'),
    'q5_8':  ('Q5. To what extent do you agree that using ChatGPT...',
              'is a useful source of insights for vacation/holiday planning'),
    # Q7 — Ease of Use (scale measures EASE not usefulness — see system prompt override)
    'q7_1':  ('Q7. How easy to use is ChatGPT for researching tourism vacations...',
              'Interaction with ChatGPT is clear and understandable'),
    'q7_2':  ('Q7. How easy to use is ChatGPT for researching tourism vacations...',
              'Interaction with ChatGPT does not require much effort'),
    'q7_3':  ('Q7. How easy to use is ChatGPT for researching tourism vacations...',
              'I find ChatGPT to be easy to use'),
    'q7_4':  ('Q7. How easy to use is ChatGPT for researching tourism vacations...',
              'ChatGPT is flexible to interact with'),
    'q7_5':  ('Q7. How easy to use is ChatGPT for researching tourism vacations...',
              'I find it easy to access the desired information through ChatGPT'),
    'q7_6':  ('Q7. How easy to use is ChatGPT for researching tourism vacations...',
              '[REVERSE SCORED: 1=I DISAGREE it is hard (=easy); 5=I AGREE it is hard (=difficult)]'
              ' It will be really hard to learn how to use ChatGPT'),
    # Q9 — AI Capability (scale_likely)
    'q9_1':  ('Q9. In your opinion, how likely is it that...',
              'AI can provide contextual destination information (weather, customs, events)'),
    'q9_2':  ('Q9. In your opinion, how likely is it that...',
              'AI-powered travel tools can provide transparent pricing and availability info'),
    'q9_3':  ('Q9. In your opinion, how likely is it that...',
              'AI can provide real-time feedback on travel decisions'),
    # Q10 — Attitude / Enjoyment (scale_agree)
    'q10_1': ('Q10. To what extent do you agree that...',
              'Using ChatGPT to learn about vacation/holiday destinations is a good idea'),
    'q10_2': ('Q10. To what extent do you agree that...',
              'ChatGPT can make my vacation/holiday experience more interesting'),
    'q10_3': ('Q10. To what extent do you agree that...',
              'Using ChatGPT makes visiting vacation/holiday destinations more fun'),
    'q10_4': ('Q10. To what extent do you agree that...',
              'I like using ChatGPT as a part of planning vacations/holidays'),
}
